// array object for orders
export default [
  {
    id: 1,
    descr: 'Laptop',
    location: 'kicukiro',
    destination: 'gasabo',
    quantity: 2,
    price: 30,
    orderDate: '2018-05-23',
    senderId: 1,
    status: 'in transit',
  },
  {
    id: 2,
    descr: 't shirts',
    location: 'kicukiro',
    destination: 'gasabo',
    quantity: 2,
    price: 30,
    orderDate: '2018-05-23',
    senderId: 1,
    status: 'in transit',
  },
  {
    id: 3,
    descr: 'phones',
    location: 'kicukiro',
    destination: 'gasabo',
    quantity: 2,
    price: 30,
    orderDate: '2018-05-23',
    senderId: 1,
    status: 'in transit',
  },
];
